
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


DO
$body$
BEGIN
    CREATE ROLE sz_re_admin WITH LOGIN CREATEDB PASSWORD 'szre123!@#';
EXCEPTION WHEN others THEN
    RAISE NOTICE 'sz_re_admin role exists, not re-creating';
END
$body$

CREATE DATABASE syzegee_rule_engine WITH OWNER = sz_re_admin ENCODING = 'UTF8' TABLESPACE = pg_default;

GRANT ALL PRIVILEGES ON DATABASE syzegee_rule_engine TO sz_re_admin;

\connect syzegee_rule_engine


CREATE TABLE SZ_RULE_PROJECT (
  PROJECT_ID BIGSERIAL NOT NULL,
  CUSTOMER_ID VARCHAR(120),
  PROJECT_CODE VARCHAR(120) NOT NULL,
  PROJECT_NAME VARCHAR(240) NOT NULL,
  PROJECT_DESC VARCHAR(240),
  IS_ACTIVE BOOLEAN,
  CREATED_BY VARCHAR(120),
  CREATED_DATE TIMESTAMP,
  UPDATED_BY VARCHAR(120),
  UPDATED_DATE TIMESTAMP,
  PRIMARY KEY (PROJECT_ID)
);

CREATE TABLE SZ_RULE (
  RULE_ID BIGSERIAL NOT NULL,
  RULE_CODE VARCHAR(120) NOT NULL,
  RULE_NAME VARCHAR(120) NOT NULL,
  RULE_DESC VARCHAR(240),
  RULE_TYPE VARCHAR(240),
  IS_ACTIVE BOOLEAN,
  CREATED_BY VARCHAR(120),
  CREATED_DATE TIMESTAMP,
  UPDATED_BY VARCHAR(120),
  UPDATED_DATE TIMESTAMP,
  PRIMARY KEY (RULE_ID)
);



CREATE TABLE SZ_RULE_DETAILS (
  RULE_DETAIL_ID BIGSERIAL NOT NULL,
  RULE_ID BIGSERIAL NOT NULL,
  RULE_DETAIL_CODE VARCHAR(120) NOT NULL,
  RULE_DETAIL_VALUE VARCHAR(240),
  IS_ACTIVE BOOLEAN,
  CREATED_BY VARCHAR(120),
  CREATED_DATE TIMESTAMP,
  UPDATED_BY VARCHAR(120),
  UPDATED_DATE TIMESTAMP,
  PRIMARY KEY (RULE_DETAIL_ID),
  CONSTRAINT SZ_RULE_FKID FOREIGN KEY (RULE_ID) REFERENCES SZ_RULE(RULE_ID)
);

CREATE TABLE SZ_PROJECT_RULES (
  PROJECT_RULES_ID BIGSERIAL NOT NULL,
  PROJECT_ID BIGSERIAL NOT NULL,
  RULE_ID BIGSERIAL NOT NULL,
  RULE_VALUE VARCHAR(120) NOT NULL,
  IS_ACTIVE BOOLEAN,
  CREATED_BY VARCHAR(120),
  CREATED_DATE TIMESTAMP,
  UPDATED_BY VARCHAR(120),
  UPDATED_DATE TIMESTAMP,
  PRIMARY KEY (PROJECT_RULES_ID),
  CONSTRAINT SZ_RULE_PROJECT_FKID FOREIGN KEY (PROJECT_ID) REFERENCES SZ_RULE_PROJECT(PROJECT_ID),
  CONSTRAINT SZ_RULE_FKID FOREIGN KEY (RULE_ID) REFERENCES SZ_RULE(RULE_ID)
);


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sz_re_admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO sz_re_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sz_re_admin;
